# Generated by Django 5.2.3 on 2025-06-10 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=10, verbose_name='niveau')),
                ('vue', models.BooleanField(default=False, verbose_name='vue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('lien', models.CharField(blank=True, max_length=200, null=True, verbose_name='lien')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
