# Generated by Django 5.2.3 on 2025-06-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreestock',
            name='annulee',
            field=models.BooleanField(default=False, help_text='Indique si cette entrée a été annulée', verbose_name='annulée'),
        ),
    ]
