# Generated by Django 5.2.3 on 2025-06-10 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('designation', models.CharField(max_length=200, verbose_name='désignation')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='quantité en stock')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=5, help_text='Seuil en dessous duquel une alerte est déclenchée', max_digits=10, verbose_name="seuil d'alerte")),
                ('unite', models.CharField(choices=[('unite', 'Unité'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('m', 'Mètre'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube')], default='unite', max_length=10, verbose_name='unité de mesure')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prix de vente')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.categorie', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée en stock'), ('sortie', 'Sortie de stock')], max_length=10, verbose_name='type de mouvement')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantité')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date du mouvement')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaire.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
